# Configuration for creation of CSV or insertion in DB of a trading pair's historical data.
# NOTE: CryptoCompare API only supports historical minute data for the past 7 days.

# -------------------GENERAL SETTINGS------------------------------------------

# (String) The base currency of the trading pair (e.g. "ETH" of "ETH/USD" pair).
base: xrp
# (String) The quote currency of the trading pair (e.g. "USD" of "ETH/USD" pair).
quote: eur
# (String) The name of the exchange to obtain historical data (e.g. "Gemini").
exchange: kraken
# (String) Time Interval to retrieve historical.  One of 'day', 'hour', 'minute'.
interval: minute
# (Int) Number of data points to return. E.g. 365 for daily will be 365 days.
# Maximum for minute data is approximately 2000 for 1.38 days worth.
limit: 2000


# ----------------CSV SETTINGS-------------------------------------------------

# (String) A custom filename.  For CSV, if not provided, the filename will be a concatenation of
# the above properties.  e.g. ethusdgeminidays30.csv
filename:
