# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: # If True, will log trades instead of executing them.

# Email configuration, and email options.
email_cfg_path: # path/to/email_cfg file.  Used to send e-mails on arb opportunities.
max_emails: # Throttles after number of sent emails for similar spreads encountered, e.g. 3
spread_rounding: # The number of decimals in which to round the spread for comparison to previous spread, e.g. 1
spread_tolerance: # The +/- of the spread in which to send an e-mail notification.
# For example, 0.5 would mean for a previous spread of 2.5%, a next spread of > 3.0% or < 2.0% would
# send an email.

# Percentage downside of limit order slippage tolerable for market order emulations
slippage: # Important for Gemini, eg. 3

# Exchange 1
exchange1: # Name of first exchange, eg. binance
exchange1_pair: # Name of target pair, eg. ETH/USDT
exchange1_test: # Whether to connect to test API, eg. true

# Exchange 2
exchange2: # Name of second exchange, eg. bithumb
exchange2_pair: # Name of target pair, eg. ETH/KRW
exchange2_test: # Whether to connect to test API, eg. false

# Targeted spreads
spread_target_low: # Target low spread after which money goes from exchange2 -> exchange1, eg. 2
spread_target_high: # Target high spread after which money goes from exchange1 -> exchange2, eg. 10

# Targeted trade amount in USD
target_amount: # eg. 50000