# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: # If True, will log trades instead of executing them.
dryrun_e1_base: # Starting base amount on e1
dryrun_e1_quote: # Starting quote amount on e1
dryrun_e2_base: # Starting base amount on e2
dryrun_e2_quote: # Starting quote amount on e2

# Email configuration, and email options.
email_cfg_path: # path/to/email_cfg file.  Used to send e-mails on arb opportunities.

# Exchange 1 - This is the exchange to be used as the default denominator.
exchange1: # Name of first exchange, eg. binance
exchange1_pair: # Name of target pair, eg. ETH/USDT
exchange1_test: # Whether to connect to test API, eg. true

# Exchange 2 - This is the exchange to be used as the default numerator.
exchange2: # Name of second exchange, eg. bithumb
exchange2_pair: # Name of target pair, eg. ETH/KRW
exchange2_test: # Whether to connect to test API, eg. false

# Historical max spread to exchange 1.
h_to_e1_max:
# Historical max spread to exchange 2.
h_to_e2_max:
# The minimum spread increment for considering trade targets.
spread_min:
# The minimum volume trade in USD.
vol_min:
# Percentage downside of limit order slippage tolerable for market order emulations
slippage: # Important for Gemini, eg. 3
