# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: true # If True, will log trades instead of executing them.
dryrun_e1_base: 100
dryrun_e1_quote: 10000
dryrun_e2_base: 100
dryrun_e2_quote: 10000000

# Email configuration, and email options.
email_cfg_path: 'configs/email_info.yaml' # path/to/email_cfg file.  Used to send e-mails on arb opportunities.

# Exchange 1
exchange1: gemini
exchange1_pair: ETH/USD
exchange1_test: false

# Exchange 2
exchange2: bithumb
exchange2_pair: ETH/KRW
exchange2_test: false

# Historical max spread to exchange 1.
h_to_e1_max: 3
# Historical max spread to exchange 2.
h_to_e2_max: 5
# The minimum spread increment for considering trade targets.
spread_min: 0.05
# The minimum volume trade in USD.
vol_min: 1000
# Percentage downside of limit order slippage tolerable for market order emulations
slippage: 3 # Important for Gemini, eg. 3

# ----------------DATABASE SETTINGS--------------------------------------------
# (String) The database name.
db_name: fcf_trade_history
# (String) The database user.
db_user: root

# ----------------TWILIO SETTINGS----------------------------------------------
# Path for the twilio config file.
twilio_cfg_path: configs/twilio/twilio.yaml
