# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: True # If True, will log trades instead of executing them.

# Email configuration, and email options.
email_cfg_path: 'configs/email_info.yaml' # path/to/email_cfg file.  Used to send e-mails on arb opportunities.
max_emails: 2 # Throttles after number of sent emails for similar spreads encountered, e.g. 3
spread_rounding: # The number of decimals in which to round the spread for comparison to previous spread, e.g. 1 for one decimal place
spread_tolerance: 0.1 # The +/- of the spread in which to send an e-mail notification.
# For example, 0.5 would mean for a previous spread of 2.5%, a next spread of > 3.0% or < 2.0% would
# send an email.

# Percentage downside of limit order slippage tolerable for emulations
slippage: 3

# Exchange 1
exchange1: gemini
exchange1_pair: ETH/USD
exchange1_test: false

# Exchange 2
exchange2: bithumb
exchange2_pair: ETH/KRW
exchange2_test: false

# Targeted spreads
spread_target_low: 0
spread_target_high: 1

# Targeted trade amount in USD
target_amount: 5