# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: true # If True, will log trades instead of executing them.

# Email configuration, and email options.
email_cfg_path: 'configs/email_info.yaml' # path/to/email_cfg file.  Used to send e-mails on arb opportunities.
max_emails: 2 # Throttles after number of sent emails for similar spreads encountered, e.g. 3
spread_rounding: # The number of decimals in which to round the spread for comparison to previous spread, e.g. 1 for one decimal place
spread_tolerance: 0.5 # The +/- of the spread in which to send an e-mail notification.
# For example, 0.5 would mean for a previous spread of 2.5%, a next spread of > 3.0% or < 2.0% would
# send an email.

# Exchange 1
exchange1: gemini
exchange1_pair: ETH/USD
exchange1_test: false

# Exchange 2
exchange2: bithumb
exchange2_pair: ETH/KRW
exchange2_test: false

# Historical max spread to exchange 1.
h_to_e1_max: 3
# Historical max spread to exchange 2.
h_to_e2_max: 5
# The minimum spread increment for considering trade targets.
spread_min: 0.05
# The minimum volume trade in USD.
vol_min: 1000
# Percentage downside of limit order slippage tolerable for market order emulations
slippage: 3 # Important for Gemini, eg. 3