# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: false # If True, will log trades instead of executing them.
dryrun_e1_base: 0
dryrun_e1_quote: 20000
dryrun_e2_base: 3
dryrun_e2_quote: 0

# Email configuration, and email options.
email_cfg_path: 'configs/email_info.yaml' # path/to/email_cfg file.  Used to send e-mails on arb opportunities.

# Exchange 1
exchange1: gdax
exchange1_pair: BTC/USD
exchange1_test: true

# Exchange 2
exchange2: gemini
exchange2_pair: BTC/USD
exchange2_test: true

# Historical max spread to exchange 1.
h_to_e1_max: 3
# Historical max spread to exchange 2.
h_to_e2_max: 50
# The minimum spread increment for considering trade targets.
spread_min: 1.7
# The minimum volume trade in USD.
vol_min: 1000000
# Percentage downside of limit order slippage tolerable for market order emulations
slippage: 0.5 # Important for Gemini, eg. 3

# ----------------DATABASE SETTINGS--------------------------------------------
# (String) The database name.
db_name: fcf_trade_history
# (String) The database user.
db_user: root
