# Exchange configurations for autotrageur.py

# Dry Run functionality.
dryrun: true # If True, will log trades instead of executing them.
dryrun_e1_base: 0
dryrun_e1_quote: 20000
dryrun_e2_base: 3
dryrun_e2_quote: 0

# Email configuration, and email options.
email_cfg_path: 'configs/email_info.yaml' # path/to/email_cfg file.  Used to send e-mails on arb opportunities.

# Exchange 1
exchange1: kraken
exchange1_pair: BTC/USD
exchange1_test: false

# Exchange 2
exchange2: bithumb
exchange2_pair: BTC/KRW
exchange2_test: false

# Historical max spread to exchange 1.
h_to_e1_max: 3
# Historical max spread to exchange 2.
h_to_e2_max: 50
# The minimum spread increment for considering trade targets.
spread_min: 0.5
# The minimum volume trade in USD.
vol_min: 25000
# Percentage downside of limit order slippage tolerable for market order emulations
slippage: 0 # Important for Gemini, eg. 3

# ----------------DATABASE SETTINGS--------------------------------------------
# (String) The database name.
db_name: fcf_trade_history_staging
# (String) The database user.
db_user: worker1

# ----------------TWILIO SETTINGS----------------------------------------------
# Path for the twilio config file.
twilio_cfg_path: configs/twilio/twilio.yaml
